//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAQ.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAQ.I18n.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AirCounterPort 的本地化字符串。
        /// </summary>
        public static string AirCounterPort {
            get {
                return ResourceManager.GetString("AirCounterPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AirLowLimit 的本地化字符串。
        /// </summary>
        public static string AirLowLimit {
            get {
                return ResourceManager.GetString("AirLowLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AirUpperLimit 的本地化字符串。
        /// </summary>
        public static string AirUpperLimit {
            get {
                return ResourceManager.GetString("AirUpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CoilModuleCode 的本地化字符串。
        /// </summary>
        public static string CoilModuleCode {
            get {
                return ResourceManager.GetString("CoilModuleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CWPlcIP 的本地化字符串。
        /// </summary>
        public static string CWPlcIP {
            get {
                return ResourceManager.GetString("CWPlcIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CWPlcPort 的本地化字符串。
        /// </summary>
        public static string CWPlcPort {
            get {
                return ResourceManager.GetString("CWPlcPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LineCode 的本地化字符串。
        /// </summary>
        public static string LineCode {
            get {
                return ResourceManager.GetString("LineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlcIP 的本地化字符串。
        /// </summary>
        public static string PlcIP {
            get {
                return ResourceManager.GetString("PlcIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlcPort 的本地化字符串。
        /// </summary>
        public static string PlcPort {
            get {
                return ResourceManager.GetString("PlcPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrinterIP 的本地化字符串。
        /// </summary>
        public static string PrinterIP {
            get {
                return ResourceManager.GetString("PrinterIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrinterPort 的本地化字符串。
        /// </summary>
        public static string PrinterPort {
            get {
                return ResourceManager.GetString("PrinterPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScanInterval 的本地化字符串。
        /// </summary>
        public static string ScanInterval {
            get {
                return ResourceManager.GetString("ScanInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SICode 的本地化字符串。
        /// </summary>
        public static string SICode {
            get {
                return ResourceManager.GetString("SICode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpindleCode 的本地化字符串。
        /// </summary>
        public static string SpindleCode {
            get {
                return ResourceManager.GetString("SpindleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StationCode 的本地化字符串。
        /// </summary>
        public static string StationCode {
            get {
                return ResourceManager.GetString("StationCode", resourceCulture);
            }
        }
    }
}
